[env:wave-tap]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/cu.usbserial-10
upload_speed = 460800
monitor_port = /dev/cu.usbserial-10
monitor_speed = 115200
lib_extra_dirs = ../lib
build_src_filter = -<*> +<wave_tap.cpp>
lib_deps =
    makuna/NeoPixelBus@^2.7.6
