[env:festicorn]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem112201
board_build.filesystem = littlefs
lib_deps = adafruit/Adafruit NeoPixel@^1.12.0
build_flags =
    -D NUM_PIXELS=150
    -D LED_PIN=1
    -D LED_TYPE=NEO_GRB+NEO_KHZ800
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
