[env:butterfly]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.7.199
board_build.filesystem = littlefs
lib_extra_dirs = ../lib
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    ayushsharma82/ElegantOTA
build_flags =
    -D NUM_PIXELS=150
    -D LED_OFFSET=41
    -D LED_PIN=1
    -D LED_TYPE=NEO_GRB+NEO_KHZ800
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
