#!/usr/bin/env python3
"""Generate festicorn's `oklch_lut.cpp` from the shared OKLCH module.

Single source of truth: `color.oklch`. Both the constant-L LUT (L=0.75
everywhere) and the variable-L LUT (hue-dependent lightness) are
emitted here so the firmware C arrays cannot drift from the Python
`RAINBOW_LUT`.

Output is byte-identical to the existing hand-curated
`festicorn/lib/oklch_lut/oklch_lut.cpp`. Run from anywhere; the path
is resolved relative to this file.

    python audio-reactive/effects/color/gen_firmware_lut.py
"""
import os
import sys

# Allow running as a script (no package context).
if __package__ in (None, ''):
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from oklch import _build_rainbow_lut, constant_lightness, lightness_for_hue
else:
    from .oklch import _build_rainbow_lut, constant_lightness, lightness_for_hue


def _format_lut(lut, array_name, entry_fmt):
    """Format a 256x3 uint8 LUT as a C `const uint8_t name[256][3] = {...};`.

    `entry_fmt` controls the per-entry spacing — const-L and var-L use
    different spacing in the original file, so they get different formats.
    """
    lines = [f"const uint8_t {array_name}[256][3] = {{"]
    for row_start in range(0, 256, 4):
        cells = [
            entry_fmt.format(r=int(lut[i, 0]), g=int(lut[i, 1]), b=int(lut[i, 2]))
            for i in range(row_start, row_start + 4)
        ]
        lines.append("    " + ", ".join(cells) + ",")
    lines.append("};")
    return "\n".join(lines)


def render_oklch_lut_cpp():
    """Build the full contents of `oklch_lut.cpp` as a string."""
    const_lut = _build_rainbow_lut(constant_lightness)
    var_lut = _build_rainbow_lut(lightness_for_hue)

    const_block = _format_lut(
        const_lut,
        "oklchConstL",
        "{{{r:3d}, {g:3d}, {b:3d}}}",
    )
    var_block = _format_lut(
        var_lut,
        "oklchVarL",
        "{{{r:3d},{g:3d},{b:3d}}}",
    )

    box = "\u2500"
    return (
        '#include "oklch_lut.h"\n'
        "\n"
        f"// {box*2} OKLCH constant-L rainbow LUT {box*35}\n"
        "// L=0.75 everywhere, per-hue max chroma (98% of gamut boundary). 256 entries.\n"
        "// OKLab -> linear sRGB -> 8-bit. No additional gamma needed.\n"
        f"{const_block}\n"
        "\n"
        f"// {box*2} OKLCH variable-L rainbow LUT {box*35}\n"
        "// Hue-dependent lightness: red (~30 deg) L~0.52, purple (~300 deg) L~0.38,\n"
        "// green/cyan/yellow L=0.75. Smooth cosine interpolation between dips.\n"
        "// Per-hue max chroma at 98% gamut boundary. Generated by audio-reactive/effects/color/gen_firmware_lut.py.\n"
        f"{var_block}\n"
    )


def _firmware_cpp_path():
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(here, "..", "..", ".."))
    return os.path.join(repo_root, "festicorn", "lib", "oklch_lut", "oklch_lut.cpp")


def main():
    out_path = _firmware_cpp_path()
    contents = render_oklch_lut_cpp()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(contents)
    print(f"Wrote {out_path} ({len(contents)} bytes)")


if __name__ == "__main__":
    main()
