; Bluetooth A2DP audio test
; Streams a sine wave to a Bluetooth speaker

[platformio]
default_envs = bt_audio

[env:bt_audio]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/cu.usbserial-0001
upload_speed = 921600
monitor_speed = 921600
board_build.partitions = huge_app.csv
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
build_flags =
    -DBOARD_HAS_PSRAM=0
